platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!

target 'GoogleSignInSwift_Example' do
  pod 'AlamofireImage'
  pod 'GoogleSignInSwift', :path => '../'
  pod 'SnapKit'

  target 'GoogleSignInSwift_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
